# Generated by Django 4.0.3 on 2022-09-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0008_suppliers_product_category_product_suppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='suppliers',
        ),
    ]
