# Generated by Django 4.0.3 on 2022-09-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0009_remove_product_category_remove_product_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
