# Generated by Django 4.0.3 on 2022-09-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0010_alter_suppliers_address_alter_suppliers_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
